spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/carry-company
    username: carry-company
    password: carry-company
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    database: postgresql

  data:
    redis:
      host: localhost
      port: 6380
      password: carry-company!