spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/comall
    username: comall
    password: comall
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    database: postgresql
# HS512
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  token-validity-in-seconds: 86400

logging:
  level:
    org.springframework.security.web: DEBUG