spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/comall
    username: comall
    password: comall
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true
    database: postgresql