spring:

  datasource:
    url: jdbc:postgresql://localhost:54321/carry-company
    username: carry-company
    password: carry-company
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    database: postgresql

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm
      time: HH:mm:ss
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  data:
    redis:
      host: localhost
      port: 6380
      password: carry-company!
# HS512
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 86400
  response:
    header: "Authorization"

logging:
  level:
    org.springframework.security.web: DEBUG

server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  shutdown: graceful
  address: localhost

  port: ${port:8080}

