spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/final-third
    username: final-third
    password: final-third
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    database: postgresql

