version: "3.7"
services:
  comall-db:
    image: postgres:14.6
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=comall
      - POSTGRES_USER=comall
      - POSTGRES_PASSWORD=comall
      - TZ=UTC
    volumes:
      - ./postgres:/var/lib/postgresql/data