version: "3.7"
services:
  final-third-db:
    image: postgres:14.6
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=final-third
      - POSTGRES_USER=final-third
      - POSTGRES_PASSWORD=final-third
      - TZ=UTC
    volumes:
      - ./postgres:/var/lib/postgresql/data